[build.env]
passthrough = [
  "CFLAGS",
  "TARGET",
  "RUST_TARGET",
  "BUILD_TARGET",
  "CARGO_BUILD_TARGET",
  "TARGET_CFLAGS",
  "CC_aarch64_unknown_linux_gnu",
  "PKG_CONFIG_SYSROOT_DIR",
  "PKG_CONFIG_ALLOW_CROSS",
  "RUSTFLAGS",
  "RUST_BACKTRACE",
  "RUST_DEBUG",
  "RUST_LOG",
  "ARCH",
  "FEATURES",
  "ROARING_ARCH",
  "TARI_NETWORK",
  "TARI_TARGET_NETWORK",
  "TARI_NETWORK_DIR",
]

# Currently needs cross-rs from git ```cargo install cross --git https://github.com/cross-rs/cross```
[target.aarch64-unknown-linux-gnu]
image.name = "ubuntu:20.04"
# targetting is needed for apple silicon
image.toolchain = ["linux/arm64=aarch64-unknown-linux-gnu", "linux/amd64=x86_64-unknown-linux-gnu"]
pre-build = "./scripts/cross_compile_ubuntu_20-pre-build.sh"

[target.aarch64-unknown-linux-gnu.env]
passthrough = [
  "CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc",
  "PKG_CONFIG_SYSROOT_DIR=/usr/lib/aarch64-linux-gnu/",
  "PKG_CONFIG_ALLOW_CROSS=true",
]

[target.x86_64-unknown-linux-gnu]
image = "ubuntu:20.04"
pre-build = "./scripts/cross_compile_ubuntu_20-pre-build.sh"

[target.x86_64-unknown-linux-gnu.env]
passthrough = [
  "PKG_CONFIG_ALLOW_CROSS=true",
]
